{{- if .Values.app.config.mongoCleanup.enabled -}}
{{ $username := default "user" .Values.app.config.mongo.auth.username }}
{{ $password := default "password" .Values.app.config.mongo.auth.password }}
{{ $hosts := join "," .Values.app.config.mongo.hosts -}}
{{ $port := default 27017 .Values.app.config.mongo.port }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "demo-crm.name" . }}-mongo-cleanup
spec:
  schedule: "{{ .Values.app.config.mongoCleanup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: {{ .Values.app.config.mongoCleanup.restartPolicy }}
          containers:
          - name: mongodb-cleanup
            image: mongo:{{ .Values.app.config.mongoCleanup.mongoVersion | default "latest" }}
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: {{ include "demo-crm.name" . }}-db-auth
            command:
            - /bin/sh
            - -c
            - mongosh -u {{ $username }} -p {{ $password }} --host "{{ $.hosts }}:{{ $port }}" --eval "db.clients.deleteMany({})"
{{- end }}
