{{ $username := default "user" .Values.app.config.mongo.auth.username }}
{{ $password := default "password" .Values.app.config.mongo.auth.password }}
{{ $hosts := join "," .Values.app.config.mongo.hosts -}}
{{ $port := default 27017 .Values.app.config.mongo.port }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-crm.name" . }}-db-auth
stringData:
  MONGODB_URI: "mongodb://{{ $username }}:{{ $password }}@{{ $hosts }}:{{ $port }}"
