apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-crm.name" . }}
  labels: {{ include "demo-crm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: app
    protocol: TCP
    name: app
  selector: {{ include "demo-crm.selectorLabels" . | nindent 4 }}
