apiVersion: v1
kind: Secret
metadata:
  name: demo-crm-infra-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:<your-username>/demo-crm-infra.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    your-private-ssh-key
    -----END OPENSSH PRIVATE KEY-----
